USE bgc;

CREATE TABLE IF NOT EXISTS USUARIOS (
		ID INT AUTO_INCREMENT PRIMARY KEY,
		DNI VARCHAR(20) NULL,
		NOMBRE VARCHAR(80) NULL,
		APELLIDO VARCHAR(100) NULL,
		FECHANACIMIENTO DATE NULL,
		FECHAREGISTRO DATETIME NULL,
		CLIENTE CHAR(10) NULL,
		FLAG BOOLEAN NULL,
		NACIONALIDAD VARCHAR(40) NULL,
		STATUS CHAR(25) NULL,
		STATUSDESCRIPTION VARCHAR(40) NULL,
		STATUSNOTE VARCHAR(800) NULL,
		CORRELATIVO VARCHAR(50) NULL,
		SCORE VARCHAR(50) NULL,
		SCORE_DESCRIPTION TEXT NULL,
		SCORE_NOTE TEXT NULL,
		RESIDENCIA VARCHAR(20) NULL,
		FECHARESPUESTA DATETIME NULL
	);